### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by auximage** [s-shin/linter-perl#24]
[Enter steps to reproduce below:]

1. Loaded a .pl file via project folder. 

**Atom Version**: 1.2.2
**System**: Mac OS X 10.11.1
**Thrown From**: [linter-perl](https://github.com/s-shin/linter-perl) package, v0.7.0

### Stack Trace

Uncaught Error: spawn EACCES

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:260

Error: spawn EACCES
    at exports._errnoException (util.js:837:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at Object.exports.spawn (child_process.js:351:9)
    at BufferedProcess.module.exports.BufferedProcess.spawn (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:188:44)
    at new BufferedProcess (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:52:14)
    at /Users/smithpj/.atom/packages/linter-perl/lib/linter-perl.coffee:105:21
    at LinterPerl.module.exports.LinterPerl.checkBLint (/Users/smithpj/.atom/packages/linter-perl/lib/linter-perl.coffee:90:9)
    at /Users/smithpj/.atom/packages/linter-perl/lib/linter-perl.coffee:85:8
    at LinterPerl.module.exports.LinterPerl.lint (/Users/smithpj/.atom/packages/linter-perl/lib/linter-perl.coffee:84:9)
    at promises.push.Promise.then._this.emitter.emit.linter (/Users/smithpj/.atom/packages/linter/lib/linter-registry.js:63:26)
```

### Commands

```
     -0:06.7.0 core:close (div.release-notes.padded.pane-item.native-key-bindings)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      "._*",
      ".svn",
      ".DS_Store",
      ".project"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "minimap"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
autocomplete-php, v0.3.7
codeigniter, v0.2.0
file-icons, v1.6.11
jquery-snippets, v11.0.0
linter, v1.11.2
linter-js-standard, v3.2.1
linter-jsonlint, v1.0.1
linter-perl, v0.7.0
php-cs-fixer, v2.5.1
project-manager, v2.6.5
remote-edit, v1.8.22
symbols-tree-view, v0.10.1
tabs-to-spaces, v1.0.0

# Dev
No dev packages
```

**Comment by s-shin** [comment]
@auximage 
Could you show me the command executed `at /Users/smithpj/.atom/packages/linter-perl/lib/linter-perl.coffee:105:21`?

It can be gotten by this process:

1. open developer tools (`Cmd+Shift+i`).
2. set a breakpoint [here](https://github.com/s-shin/linter-perl/blob/v0.7.0/lib/linter-perl.coffee#L105).
3. reload atom (`Ctrl+Alt+Command+l`).
4. Atom will stop at the breakpoint, so `command` and `args` can be referred.

Regards,

**Comment by auximage** [comment]
I don’t know if this gives you what you need or not..

**Comment by s-shin** [comment]
Thanks! I could make sure `perldoc` command is built correctly by the image.

But hmm... I'm having no idea about the reason of `spawn EACCES`.
In general, an EACCES error occurs by a permission issue though, would you have any idea?

**Comment by auximage** [comment]
I would have absolutely no idea..   lowly user here.   (c:
