### ISSUE TITLE
Error: Missing html/text field on Linter Response

### ISSUE THREAD

**Issue by fzzr-** [s-shin/linter-perl#30]
```log
Error: Missing html/text field on Linter Response
    at /Users/fzzr/.atom/packages/linter/lib/validate.coffee:40:19
    at Array.forEach (native)
    at Object.module.exports.Validate.messages (/Users/fzzr/.atom/packages/linter/lib/validate.coffee:27:14)
    at MessageRegistry.set (/Users/fzzr/.atom/packages/linter/lib/message-registry.js:36:16)
    at /Users/fzzr/.atom/packages/linter/lib/linter.coffee:37:17
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Users/fzzr/.atom/packages/linter/lib/linter-registry.js:66:26
```

After clean installation without any changes, happening for any `.pm` file.

**Comment by s-shin** [comment]
Closed by #31.
